version: "3.9"

services:
  webserver:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/var/www/html
      - ./config/php/php.ini:/etc/php8/conf.d/50_xdebug.ini
      - ./config/apache:/app/config/apache
      - ./config/apache/httpd.conf:/etc/apache2/httpd.conf
      - ./config/supervisor:/etc/supervisor
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=storage
      - DB_PORT=5432
    container_name: webserver    
    hostname: webserver
    extra_hosts:
      - "dev.docker.com.br:127.0.0.1"
  database:
    image: library/postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=storage
      - POSTGERS_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: database
    hostname: database

volumes:
  pgdata: